# Generated by Django 6.0.1 on 2026-04-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['car_model', 'date'], name='app_sale_car_mod_168f05_idx'),
        ),
    ]
